-- Script de configuración para sistema de ventas
-- Oracle Autonomous Database 19c

-- Eliminar secuencias si existen (para reinicios)
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE PRODUCTO_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE VENTA_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE DETALLE_VENTA_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Eliminar tablas si existen (para reinicios)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DETALLE_VENTAS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE VENTAS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PRODUCTOS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Crear secuencias para IDs
CREATE SEQUENCE PRODUCTO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE VENTA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE DETALLE_VENTA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Crear tabla de productos
CREATE TABLE PRODUCTOS (
    ID NUMBER(10) PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    CATEGORIA VARCHAR2(50) NOT NULL,
    PRECIO NUMBER(10,2) NOT NULL,
    STOCK NUMBER(5) NOT NULL,
    DESCRIPCION VARCHAR2(255)
);

-- Crear tabla de ventas
CREATE TABLE VENTAS (
    ID NUMBER(10) PRIMARY KEY,
    FECHA TIMESTAMP NOT NULL,
    TOTAL NUMBER(10,2) NOT NULL,
    CLIENTE_NOMBRE VARCHAR2(100),
    CLIENTE_RUT VARCHAR2(12),
    VENDEDOR VARCHAR2(100)
);

-- Crear tabla de detalle de ventas
CREATE TABLE DETALLE_VENTAS (
    ID NUMBER(10) PRIMARY KEY,
    VENTA_ID NUMBER(10) NOT NULL,
    PRODUCTO_ID NUMBER(10) NOT NULL,
    CANTIDAD NUMBER(5) NOT NULL,
    PRECIO_UNITARIO NUMBER(10,2) NOT NULL,
    SUBTOTAL NUMBER(10,2) NOT NULL,
    CONSTRAINT FK_DETALLE_VENTA FOREIGN KEY (VENTA_ID) REFERENCES VENTAS(ID),
    CONSTRAINT FK_DETALLE_PRODUCTO FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(ID)
);

-- Insertar datos de prueba para productos
INSERT INTO PRODUCTOS (ID, NOMBRE, CATEGORIA, PRECIO, STOCK, DESCRIPCION)
VALUES (PRODUCTO_SEQ.NEXTVAL, 'Alimento para perros premium', 'Alimentos', 25000, 50, 'Alimento premium para perros adultos - 15kg');

INSERT INTO PRODUCTOS (ID, NOMBRE, CATEGORIA, PRECIO, STOCK, DESCRIPCION)
VALUES (PRODUCTO_SEQ.NEXTVAL, 'Pelota para perros', 'Juguetes', 5000, 30, 'Pelota de goma resistente para perros');

INSERT INTO PRODUCTOS (ID, NOMBRE, CATEGORIA, PRECIO, STOCK, DESCRIPCION)
VALUES (PRODUCTO_SEQ.NEXTVAL, 'Correa para paseo', 'Accesorios', 12000, 25, 'Correa retráctil para paseos de hasta 5 metros');

INSERT INTO PRODUCTOS (ID, NOMBRE, CATEGORIA, PRECIO, STOCK, DESCRIPCION)
VALUES (PRODUCTO_SEQ.NEXTVAL, 'Cama para gatos', 'Accesorios', 18000, 15, 'Cama acolchada para gatos de tamaño mediano');

INSERT INTO PRODUCTOS (ID, NOMBRE, CATEGORIA, PRECIO, STOCK, DESCRIPCION)
VALUES (PRODUCTO_SEQ.NEXTVAL, 'Shampoo para mascotas', 'Higiene', 8000, 40, 'Shampoo hipoalergénico para perros y gatos');

COMMIT;
